
version: '3.4'

services:
  rinhainterpreterapp:
    image: rinhainterpreterapp
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
